# Generated by Django 5.2.1 on 2025-06-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do setor')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do setor')),
            ],
        ),
    ]
