# Generated by Django 5.2.1 on 2025-06-09 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do sensor')),
                ('sensor_type', models.CharField(max_length=255, verbose_name='Tipo do sensor')),
                ('unity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidade de medida de referência')),
                ('installation_date', models.DateField(verbose_name='Data de instalação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sensor_monitoring.department')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
    ]
