# Generated by Django 5.2.1 on 2025-06-16 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_monitoring', '0002_alter_department_options_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sensor_monitoring.department', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='SensorRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor da leitura')),
                ('read_time', models.DateTimeField(verbose_name='Tempo da leitura')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_monitoring.sensor', verbose_name='Sensor')),
            ],
        ),
    ]
